name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: install dependencies
      run: sudo apt install --yes --no-install-recommends libboost-coroutine-dev
    - name: checkout
      uses: actions/checkout@v1
    - name: checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: configure
      run: cmake -H. -Bbuild
    - name: build
      run: cmake --build build
    - name: unit tests
      run: cd build && ctest --output-on-failure 
